apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hf7sw11kl-go 
  janus-idp.io/tekton: hf7sw11kl-go
  backstage.io/kubernetes-id: hf7sw11kl-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hf7sw11kl-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  