apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: hf7sw11kl-go-gitops
  description: This is GitOps manifest for hf7sw11kl-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: hf7sw11kl-go
    backstage.io/kubernetes-id: hf7sw11kl-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: hf7sw11kl-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:hf7sw11kl-go
