apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hf7sw11kl-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hf7sw11kl-go 
  name: hf7sw11kl-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hf7sw11kl-go 
